name: fnlapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie: ^3.1.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  universal_platform: ^1.1.0
  intl: ^0.17.0
  http: ^1.2.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  liquid_progress_indicator_v2: ^0.5.0
  font_awesome_flutter: ^10.0.0
  sqflite: ^2.0.0+4
  web_socket_channel: ^2.1.0
  timezone: ^0.8.0
  flutter_tts: ^4.0.2
  url_launcher: ^6.1.10
  video_player: ^2.5.1
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
